### ISSUE TITLE
Update all links once github and biorxiv are ready

### ISSUE THREAD

**Issue by shashwatsahay** [HiDiHlabs/ssam-lite#7]

**Comment by shashwatsahay** [comment]
@sebastiantiesmeyer 

"Naveed says that we should link to our own github page/publication, even though I think a tip to the head to Jeongbin (who conceived the algorithm) is not inappropriate. And it kind of seems the natural thing to do - after having tried out our html-based version, wouldn't you want to move on the the git of the 'real thing' instead of cloning another ssamLite?"

**Comment by shashwatsahay** [comment]
@niklasmueboe 

"If you want we can link to his GitHub in the About, but in the footer I think it is confusing as you expect it to be the github from the tool you are using"

**Comment by niklasmueboe** [comment]
Only link missing is bioRxiv, ReadTheDocs, GitHub and Zenodo already correct
