### ISSUE TITLE
Consistent Name Usage 

### ISSUE THREAD

**Issue by shashwatsahay** [HiDiHlabs/ssam-lite#8]
Currently we basically have everything like ssamLite, SSAMlite, SSAM-lite, ....

**Comment by shashwatsahay** [comment]
The naming paradigm to follow is ssam-lite-solo

**Comment by niklasmueboe** [comment]
I already changed it in the html and Docs

**Comment by naveedishaque** [comment]
agreed on "ssam-lite" and "ssam-lite-server"
